window.LEAGUES = [
  "Albania, Kategoria Superiore",
  "Andorra, Primera Divisio",
  "Armenia, Armenian Premier League",
  "Austria, Austrian Bundesliga",
  "Azerbaijan, Azerbaijan Premier League",
  "Belarus, Belarusian Premier League",
  "Belgium, Belgian Pro League",
  "Bosnia and Herzegovina, Premier League of Bosnia and Herzegovina",
  "Bulgaria, First Professional Football League",
  "Croatia, Croatian First Football League (HNL)",
  "Cyprus, Cypriot First Division",
  "Czechia, Czech First League",
  "Denmark, Danish Superliga",
  "England, Premier League",
  "Estonia, Meistriliiga",
  "Faroe Islands, Faroe Islands Premier League",
  "Finland, Veikkausliiga",
  "France, Ligue 1",
  "Georgia, Erovnuli Liga",
  "Germany, Bundesliga",
  "Gibraltar, Gibraltar Football League",
  "Greece, Super League Greece",
  "Hungary, Nemzeti Bajnoksag I",
  "Iceland, Urvalsdeild",
  "Israel, Israeli Premier League",
  "Italy, Serie A",
  "Kazakhstan, Kazakhstan Premier League",
  "Kosovo, Football Superleague of Kosovo",
  "Latvia, Latvian Higher League",
  "Liechtenstein, Liechtenstein Cup (no league)",
  "Lithuania, A Lyga",
  "Luxembourg, National Division",
  "Malta, Maltese Premier League",
  "Moldova, Moldovan Super Liga",
  "Montenegro, Montenegrin First League",
  "Netherlands, Eredivisie",
  "North Macedonia, Macedonian First Football League",
  "Northern Ireland, NIFL Premiership",
  "Norway, Eliteserien",
  "Poland, Ekstraklasa",
  "Portugal, Primeira Liga",
  "Republic of Ireland, League of Ireland Premier Division",
  "Romania, Liga I",
  "Russia, Russian Premier League",
  "San Marino, Campionato Sammarinese di Calcio",
  "Scotland, Scottish Premiership",
  "Serbia, Serbian SuperLiga",
  "Slovakia, Slovak Super Liga",
  "Slovenia, Slovenian PrvaLiga",
  "Spain, LaLiga",
  "Sweden, Allsvenskan",
  "Switzerland, Swiss Super League",
  "Turkey, Super Lig",
  "Ukraine, Ukrainian Premier League",
  "Wales, Cymru Premier"
];
